spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kingdom_wars_db
    username: kingdom_wars_admin
    password: kingdom_wars_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
