spring:
  application:
    name: kingdomwars

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - env
          - loggers
  endpoint:
    health:
      show-details: always

server:
  port: 8080
